# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3af171dcf133aba55e4ef38689a883fafa9ad231c78ea7fa14683bc5a2cc9591e5efa9a948b120a84d2c6a192c0f80115627719ca5126c49251407019127c88a

test:
  secret_key_base: d50e71df82513bc7c2578b07b720b35d0fc2a3f3b8b33cb30de289aef56a101f3c764595bdc8cf5caa8ac64c1b1f77d95f93e8dc04f53eb0e9bc34711ca9c385

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
